### ISSUE TITLE
cannot export pdf when folder path isn’t on drive c:

### ISSUE THREAD

**Issue by abechanta** [abechanta/vscode-ext-paged-media#1]

**Comment by techlabxe** [comment]
ご報告ですがドライブ C に作業フォルダを移動したら、無事にPDFが生成できました。

**Comment by abechanta** [comment]
https://gitlab.pagedmedia.org/tools/pagedjs-cli/issues/27

to be fixed, we also have to omit the workaround at ./ext-exporter.js:Line46.
```
		// NOTE: workaround for pagedjs-cli.
		// ---> pass "uri.fsPath.replace(...)" instead of "uri.fsPath"
		// this will surpress unexpected progress stopping when launching chromium.
		//
		// const proc = child_process.spawn("node", [cli, "--inputs", uri.fsPath, "--output", pdf.fsPath, ], { encoding: "utf8", cwd: context.extensionPath, });
```

**Comment by abechanta** [comment]
at branch "fix/cannot-export-pdf"

we've taken another workaround to solve this issue.
we've changed the cwd value of spawning from "context.extensionPath" to root folder of the drive where the input file exists.
